### ISSUE TITLE
Larivaar mode displays strange characters

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/anvaad-js#86]
Larivaar mode displays strange characters

![image](https://user-images.githubusercontent.com/6245927/79673946-0858cb00-81fc-11ea-8e78-41527c17b5ff.png)

1. Open https://www.sikhitothemax.org/ang?source=G&ang=516
2. Enable Larivaar. Please observe strange characters

**Comment by tsingh777** [comment]
Think this is fixed. @plug-n-play can we close?

**Comment by plug-n-play** [comment]
@tsingh777 It's still present when we chose font face as Unicode
